Kwf/Controller/Action/Cli/Web/ClearCacheWatcherController.php
Kwf/Util/Proc.php
composer.json

Uses python watchdog (http://pythonhosted.org/watchdog/)
Watchdog supports Linux, OS X and Windows using their native file watching api.
Unfortunately there is no such library for nodejs which would be easier to install (as we require npm already).
But this is a completely optional dependency for development only...
Also add new dependency: Symfony Process to start the watcher process
This doesn't work with Php 5.2 but we need it for development only

Add second file watcher backend to clear-cache-watcher: watchmedo

---

Kwf_js/Utils/Element.js

When using "CallOnContentReady", the function "kwf.Util.ResponsiveImg" in ResponsiveImg.js will be used.
This function then calls "isVisible()" on an Element. In that function, the tagname of the element will be
used, but in some case "el.tagName" doesnt return an string and IE8 shows an error.

IE8 fix when isVisible() is called on an Element that has no tagname

---

Kwf/Loader.php

For classes like PHPExcel, TCPDF etc.
The old version was only able to load class that startet with Class_

Fix the Kwf Loader, so that classes without _ also get loaded

---

Kwf/Assets/Provider/BowerBuiltFile.php

This was needed for excel-builder. It was also needed to add this
at the first position because there is an excel-builder.js file at
root level using requireJS which doesn't work for us. We need to
work with "dist/excel-builder.dist.js"

Add new place to look for js file

---

Kwf/Assets/Provider/BowerBuiltFile.php

Instead of brute force trying all different names use main property of bower.json.
This might not work correctly in all cases.
Keep the old code if no bower.json exists

Improve BowerBuiltFile: use main property from bower.json

---

Kwf/Model/Db.php
config.ini

If buffers are not written for some reason (error, script aborts etc) we get noticed about that.
Disabled by default

Add debugging code that verifys Db buffer is written out correctly

---

Kwf/Form/Field/MultiCheckbox.php

Problem on page with multiple forms containing multicheckbox for same
relationToValuesRule. Results in deleting relation-rows in submited
form (no problem with the first form on page) after changing values.
The reason was that on page load every form is initialised and therefore
fieldKey for multicheckbox#2 is form_RELATION2_ID. In post-request only
posted form ist initialised and therefore multicheckbox in form#2 is called
form_RELATION_ID and does not match with post-variables with value
form_RELATION2_ID

Don't use static array to define fieldKey. Give option to set manually

---

Kwf/Controller/Action.php
Kwf/Rest/Controller.php

This is useful for frontend developement with apis
e.g. jquery: use the setRequestHeader method in $.ajaxSend

Allow kwfSessionToken as header Param

---

Kwf/Trl/Parser/JsParser.js

If input is written in chunks only the first was parsed, resulting
in exception.

JS-Parser: Concat all input before parsing js-code

---

Kwc/Columns/Component.scss

When a column component with properties 25-25-25-25 is used and its parent is between 480 and 621 pixels wide, than it looks like a two column component. Problem is: when the content of the first element is higher than the second one, than the third element will move to the right edge, because of an missing "clear" setting in css. This commit should fix this wrong behavior.

Column-Component responsive fix

---

Kwf/Form/Field/File.php
Kwf_js/Form/File.js

because other image types don't make sense on a website.

AllowOnlyImages only allows png, gif and jpg

---

Kwf/Model/Abstract.php
tests/Kwf/Model/FnF/NumberCompare/Test.php

This does only falsify the correct result. Was initially wrong.
Introduced in 74e7cbdfb851888bae3e64fd4b4de088bea837e2

Remove || !$value from return value

---

Kwf/View/Helper/Image.php

because $this->_getAssetPath does return path without /.
So string does not match, does not get replaced, checking for
none-dpr2 image-path.

Remove / before replace string to check dpr2-image existing

---

Kwf/Loader.php
tests/Kwf/Loader/Test.php

PHPExcel is a special case because it uses _ for namespaces but does
not contain _ in composer.json autoload definition and has a class
matching namespace (PHPExcel.php and other classes in folder PHPExcel)
Fixes issue #357

Improve Kwf_Loader to enable loading PHPExcel

---

Kwf/Assets/ResponsiveEl/JsDependency.php
Kwf/Assets/ResponsiveEl/Provider.php
sass/Kwf/stylesheets/kwf/_el-breakpoint.scss
sass/Kwf/stylesheets/kwf/_responsive-el.scss
tests/Kwf/Assets/ResponsiveEl/Foo.scss
tests/Kwf/Assets/ResponsiveEl/Test.php
tests/Kwf/Assets/ResponsiveEl/TestDependencies.ini
tests/Kwf/Assets/ResponsiveEl/TestProviderList.php

JavaScript is generated based on mixin output. This avoids the need for Component.js containing ResponsiveEl only.
usage example:
.cssClass {
@include responsive-el(350px) {
p  { color: red; }
}
}

Implement sass mixin for Responsive El

---

Kwc/Advanced/GoogleMapView/Component.printcss
Kwc/Advanced/GoogleMapView/Component.scss
Kwc/Articles/Detail/Component.css
Kwc/Articles/Detail/Component.printcss
Kwc/Basic/ImageEnlarge/Component.printcss
Kwc/Basic/ImageEnlarge/Component.scss
Kwc/Paging/Abstract/Component.css
Kwc/Paging/Abstract/Component.printcss
Kwc/Tags/Component.scss
Kwf/Assets/Dependency/File.php
Kwf/Assets/Dependency/File/PrintCss.php
Kwf/Assets/Dispatcher.php
Kwf/Assets/Loader.php
Kwf/Assets/Package.php
Kwf/Assets/Provider/Components.php
Kwf/Component/Settings.php
Kwf/Controller/Action/Debug/AssetsDependenciesController.php
Kwf/Util/ClearCache/Watcher.php
Kwf/View/Helper/Assets.php

Instead use @media print which is supported in IE9+
This change is possible since we don't support IE8 anymore.
kwf-upgrade script will automatically convert all .printcss

Remove printcss assets filetype

---

Kwc/Abstract.php
Kwf/Assets/Components/Dependency/Abstract.php
Kwf/Assets/Components/Dependency/Css.php
Kwf/Assets/Components/Dependency/Js.php
Kwf/Assets/Components/Provider.php
Kwf/Assets/Dependency/File/Css.php
Kwf/Assets/Dependency/File/Js.php
Kwf/Assets/Dependency/File/Scss.php
Kwf/Assets/Package/TestPackage.php
Kwf/Assets/ProviderList/Default.php
Kwf/Assets/ProviderList/Test.php
tests/Kwf/Assets/Components/ProviderTestDependencies.ini
tests/Kwf/Assets/Components/Root.php
tests/Kwf/Assets/Components/Test.php
tests/Kwf/Assets/Components/TestComponent1/Component.php
tests/Kwf/Assets/Components/TestComponent1/Component.scss
tests/Kwf/Assets/Components/TestComponent2/Component.php
tests/Kwf/Assets/Components/TestComponent2/Component.scss
tests/Kwf/Assets/Components/TestComponent3/Component.php
tests/Kwf/Assets/Components/TestComponent3/Component.scss
tests/Kwf/Assets/Components/TestProviderList.php
tests/Kwf/Assets/Dependency/Test.php
tests/Kwf/Assets/DependencyWithComponents/TestProviderList.php

Instead of generating multiple classes in html duplicate the styles.
Example vwpkw5 css:
before:
rules: 1025
size: 152k
size zip: 18k
after:
rules: 1384    (+35%)
size: 177k     (+16%)
size zip: 19k  (+4%)

Change implementation of how inherited Component styles are applied

---

Kwf/Model/Db.php
tests/Kwf/Model/Db/ExpressionTest.php
tests/Kwf/Model/DbWithConnection/ExprChildSum/BarModel.php
tests/Kwf/Model/DbWithConnection/ExprChildSum/Test.php

Current behaviour was "SELECT ... WHERE (a OR b = 0)", correct
behaviour is "SELECT ... WHERE (a OR b) = 0"

Evaluate And/Or expressions correctly when used as condition

---

Kwf/Model/Db.php
Kwf/Model/Union.php
tests/Kwf/Model/Union/Abstract/Test.php
tests/Kwf/Model/Union/Db/ModelSibling.php
tests/Kwf/Model/Union/DbWithExpr/Test.php
tests/Kwf/Model/Union/DeletedFlag/Model2.php
tests/Kwf/Model/Union/FnF/ModelSibling.php

Support IsNull-Expression for Sibling Row - even though sibling row doesn't exists, parent row has to be returned

Improve handling of sibling rows in Union Model

---

Kwc/FulltextSearch/Search/Detail/Component.tpl
Kwf/View/Helper/HighlightTerms.php
tests/Kwf/View/HighlightTermsTest.php

Change highlightingTerms function to always get resulttext with the searchterms in it.
Change highlighting to hihglight all partials of the searchterms, not only the exact alone standing word.
This behavior can be changed with the "highlightWordPartial" option.
Add a Test to check if the resulttext has the searchterms in it.

Change highlighting of searchresults and searchresults text itself

---

Kwc/Abstract/Image/Component.php
Kwc/Basic/Image/Component.php
Kwf/Controller/Action/Cli/Web/UpdateUploadsController.php
Kwf/Media/Image.php
Kwf/Media/Output/Component.php
Kwf/Update/20150309Legacy39000.php
Kwf/Update/20151012UploadsDimensions.php
Kwf/Uploads/Row.php

With that we don't have to touch the upload files during view rendering at all. That improves performance if the uploads are on a slow filesystem (NFS)

Add image dimensions to uploads table

---

Kwc/Paragraphs/Panel.js

Else store adds meta=undefined resulting in missing meta param for
first request.

Set copy of baseParams not same object.

---

Kwf/Util/Fulltext/Backend/Solr.php
config.ini

solr on production and test is always configured differently per web
this way config-setting for local development doesn't need to be
reset to default in every web.

Add additional config-setting to simplify solr configuration

---

Kwc/Menu/Expanded/ParentMenu/Trl/Component.php

Else code in Kwc_Menu_Expanded_EditableItems_Trl_Component crashes
if no subpages visible. According to Kwc_Menu_Expanded_ParentMenu_Component
isset should be checked.

Only call _attachEditableToMenuData for submenu if submenu set

---

Kwc/Form/Component.php
Kwc/Shop/AddToCartAbstract/Trl/Form/Component.php

This results in problems with trl component getting already translated
form not able to retranslate. Now this is done in processInput and
getTemplateVars because data is correct.

Dont do trlStaticExecute in getForm()

---

Kwc/Columns/Abstract/Component.php

- This improves performance as less different classes exist statically
- Fixes problems if the outer paragraphs does custom stuff we don't want in a column again

Columns: don't use parentComponentClass, instead hardcode Paragraphs

---

Kwc/User/Login/Component.php
Kwf/User/Auth/Interface/Redirect.php
Kwf/User/Auth/Proxy/Redirect.php
Kwf/User/Auth/Union/Redirect.php

Saml2 needs to do a post to a defined url containing SAMLRequest
data. This isn't possible with GET of an url. Now it's possible
to define html to be output to do so. GetUrl should return false
to indicate html is needed.

Add getHtml function to auth-interface to enable saml2 login-post

---

Kwc/Abstract/Image/Component.php
Kwc/Form/Component.twig
commonjs/frontend-form/form.js
commonjs/responsive-img.js

With multiple images on a page, multiple loadinganimation will be animated.
This causes overall animation performance issues, for example with parallax effekt on a big image.

Add and animate loadinganimation only when it comes into view.

---

Kwc/Form/Field/Abstract/Component.php
Kwc/Form/Field/Abstract/Trl/Component.php

trlStaticExecute is only called if form is not cached. getFormField
is always called so also call trlStaticExecute. Fixes problems
introduced with 61ab772704dc34aa57696b4a3daab3de97afed50

Text is masked on cached form

---

Kwc/Root/DomainRoot/Model.php
Kwf/Component/Data.php
Kwf/Util/Apc.php
Kwf/Util/Https.php
Kwf/Util/Setup.php
config.ini

- used when creating preview url in admin
- allows us to set domain to the correct domain which doesn't yet point to us and use preliminaryDomain during that time
- preliminaryDomain doesn't have to match in pattern
other ideas for naming:
- interimDomain
- temporaryDomain
- provisionalDomain

Add preliminaryDomain config setting

---

Kwf/Update/20150309Legacy39000.php

Breaking change in 5.7:
```
Columns in a PRIMARY KEY must be NOT NULL, but if declared explicitly as NULL produced no 
error. Now an error occurs. For example, a statement such as CREATE TABLE t (i INT NULL 
PRIMARY KEY) is rejected. The same occurs for similar ALTER TABLE statements. 
(Bug #13995622, Bug #66987, Bug #15967545, Bug #16545198)
```
Error message:
https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html#error_er_primary_cant_have_null
Screen from  kwf-app-demo ext 4 branch installation:
How `kwf_uploads` looks after fix:
p.s. How to enable fix from 3.9 branch to other (3.10, 3.11 etc) branches? =)

Fix MySQL 5.7 error 42000 in update script

---

Kwf/Form/Field/ShowSelect.php

If id is `NULL` with `setReference` it shows error:
```
exception 'ErrorException' with message 'Call to a member function __toString() on null' in
C:\OpenServer\domains\aviashelf\vendor\koala-framework\koala-framework\Kwf\Form\Field\
ShowSelect.php:42
```
Related to my comment:
https://github.com/koala-framework/koala-framework/issues/516#issuecomment-218375020

Fix NULL relation error in ShowSelect

---

Kwc/User/Login/Component.twig

this simplifies the code in every web to style login page because
redirects-block shouldn't be needed to change.

Add div around button to be more flexible with styling,

---

Kwf/Model/Abstract.php
Kwf/Model/Provider/Abstract.php
Kwf/Model/Provider/ClassNames.php
Kwf/Model/Provider/Components.php
Kwf/Model/Provider/Default.php
config.ini

This feature is required for packages to support update-scripts for
models not connected to any component.
Code to find models moved to corresponding model-provider.
Helper function to find relation-models moved into modelProviderAbstract

Implement modelProviders

---

Kwf/Controller/Action/Cli/Web/SetupController.php
Kwf/Controller/Action/Cli/Web/UpdateController.php
Kwf/Controller/Action/Maintenance/SetupController.php
Kwf/Controller/Action/Maintenance/UpdateController.php
Kwf/Update/20150309Legacy38004.sql
Kwf/Update/20160715KwfUpdates.php
Kwf/Util/Update/Helper.php
Kwf/Util/Update/Runner.php
Kwf/Util/Update/UpdatesModel.php

- much nicher to check executed updates
- fixes possible issue when serialized string is larger than mysql max_allowed_packet
Default max_allowed_packet is 1MB which can be reached with larger webs

Convert kwf_update table to kwf_updates containing a row per update

---

Kwf/Util/Fulltext/Backend/Solr.php

Only highest subroots are returned because domain does not have
extra solr-core if there is master and trl. Current implementation
does only support flat subroot structure.

Reduce fulltext base subroots

---

Kwf/Util/Apc.php

This enables https support for local development without providing
valid certificates. There should also be no security problem because
normally it's only called internal of the dmz.

Ignore https errors for clear-cache.

---

Kwf/Assets/Dependency/File/Css.php

In some css files of external repositories @charset is defined. This
does crash our build.
Only removing @charset utf8 because if other charset is used there
might be encoding bugs because we generate a single css file in utf8.

Remove @charset utf8 from css-files because it does crash build

---

Kwc/Abstract/Image/Component.twig
Kwc/Basic/ImageEnlarge/Component.tpl
Kwc/Basic/ImageEnlarge/EnlargeTag/ImagePage/Component.tpl
Kwf/Media/Image.php
Kwf/Media/Output/Component.php
commonjs/responsive-img.js

Instead of 100px steps increase step size based on width:
- 1000: ~100
- 2000: ~200
- 3000: ~400
- 4000: ~700
This results in:
7680 width: 24 instead of 76 different sizes
3600 width: 21 instead of 36 different sizes

Responsive Image: less steps in widths

---

Kwf/Util/Setup.php

This is required to enable mobile-apps to send oauth and preLogin
at the same time.

Add option to set preLogin values in X-Authorization-Header

---

commonjs/responsive-img.js

If an element comes into view without scrolling, for example in a slider, it has to be removed from deferedImages array.
Because orientationchange triggers a scrollevent on some devices, a check has to be made if the element is not already initialized in the showImageWhenVisible function.

Fix duplicated imagetags

---

Kwc/Basic/LinkTag/Abstract/Mail.html.tpl
Kwc/Basic/LinkTag/Abstract/Mail.txt.tpl
Kwc/Guestbook/ActivatePost/Component.php
Kwc/Guestbook/Mail/Mail.txt.tpl
Kwc/Guestbook/Write/Form/Component.php
Kwc/Mail/Abstract/Component.php
Kwc/Mail/PlaceholdersPlugin.php
Kwc/Mail/Redirect/Component.php
Kwc/Mail/Redirect/ContentSender.php
Kwc/Mail/Redirect/Update/20150309Legacy30442.sql
Kwc/Mail/Redirect/Update/20150309Legacy30443.sql
Kwc/Newsletter/Detail/Mail/Paragraphs/LinkTag/EditSubscriber/Mail.html.tpl
Kwc/Newsletter/Detail/Mail/Paragraphs/LinkTag/EditSubscriber/Mail.txt.tpl
Kwc/Newsletter/Detail/Mail/Paragraphs/LinkTag/Unsubscribe/Mail.html.tpl
Kwc/Newsletter/Detail/Mail/Paragraphs/LinkTag/Unsubscribe/Mail.txt.tpl
Kwc/Newsletter/Detail/StatisticsController.php
Kwc/Newsletter/EditSubscriber/Component.php
Kwc/Newsletter/Subscribe/Component.php
Kwc/Newsletter/Subscribe/DoubleOptIn/Component.php
Kwc/Newsletter/Subscribe/Mail/Mail.html.tpl
Kwc/Newsletter/Subscribe/Mail/Mail.txt.tpl
Kwc/Newsletter/Unsubscribe/Component.php
Kwc/Newsletter/Update/20150309Legacy34703.sql
Kwf/Component/View/Helper/ComponentLink.php
tests/Kwc/Mail/Redirect/Content/Mail.html.tpl
tests/Kwc/Mail/Redirect/Content/Mail.txt.tpl

- drop showcomponent type in redirects, replaced by passMailRecipient flag
processMailRedirectInput replaced by processInput plus call to Kwc_Mail_Redirect_Component::parseRecipientParam
- don't add `*redirect*` to urls in mail, now all urls will get redirect
- html will be searched for <a href=""
- text will be search for http://... (absolute urls for internal links are required)
- drop title for redirects
was never really used and is not possible anymore without `*redirect*`
- The mail now can link to it's own page providing a *personalized* version of the mail
whith all placeholders and redirect links working correctly

Major change to Mail Redirects making it possible to show a webversion of newsletter in browser

---

Kwf/Acl/Resource/MediaUpload.php
Kwf/Acl/Resource/MediaUpload/Image.php
Kwf/Controller/Action/Media/UploadController.php

usage exampe:
$this->addResource(new Kwf_Acl_Resource_MediaUpload('upload_image', 'image/.*', '(jpe?g|png|gif)$', 1024*1024*10));
or (the same):
$this->addResource(new Kwf_Acl_Resource_MediaUpload_Image('upload_image', 1024*1024*10));
(10MB is the maximum file size (optional))

Add possibility to restrict uploads to mime type, filename and maximum size

---

Kwf/Model/Abstract.php
KwfBundle/Validator/Constraints/NoTags.php
KwfBundle/Validator/Constraints/NoTagsValidator.php

This is a central solution to validate tags for all symfony-rest
controllers. The same validation is already in use for kwf-form-fields.
It's possible to allow tags by adding "allowTags" = true to column
in serialization definitions.

Add default but optional noTags-validation to model

---

Kwf_js/Form/FileUploadWindow.js

because if using formPanel with fileUpload does result in POSTing
iFrame and unparsable json-response identified as html. Disadvantage
is file gets already uploaded on selection, but this is default
behaviour of kwf.file formfield.
Result returned on "uploaded" event is compatible with old version.

FileUploadWindow: Change ext field-type to kwf.file,

---

Kwf/Media.php

fixes a bug reported by franz where specific mediaCache-folder had
too many entries.

Group mediaCache entries into subfolders to reduce entries per folder

---

Kwc/Menu/Abstract/Component.scss

The structur in our mainmenu is like nav.kwcClass->ul.menu->li.item. For this constellation the css, wish shows or hides the menuitems according to the pagesettings from the backend, had no effect.
Now the css should be applied on all items in all levels.

Fix show and hide options for menuentries on mobile to work again.

---

Kwc/Abstract/Image/Component.php
Kwc/Basic/DownloadTag/Component.php
Kwf/Media.php
Kwf/Media/CollectGarbageMaintenanceJob.php
Kwf/Media/Output/ClearCacheInterface.php

Iterates over directories and files and check if MediaOutput implements
ClearCacheInterface. It's not called for every type because in most
cases it's all or nothing and it doesn't hurt if there are a few more
entries.

MediaCache: Implement collectGarbage maintenanceJob

---

Kwf/Util/Maintenance/Dispatcher.php
config.ini

Fail notifications are enabled on production and disabled on test by default.

Add config setting to disable fail notifications of maintenance jobs

---

KwfBundle/EventListener/CsrfProtection.php
KwfBundle/Resources/config/services.yml

This event listener throws and access denied error if the request does not have the X-Requested-With:XMLHttpRequest header.
If the API is used by any external service lika a native app, you have to override the service and implement your own whitelist.

Add CSRF Protection Event Listener to KwfBundle

---

Kwc/User/Activate/Form/Component.php
Kwc/User/Activate/Form/Success/Component.php
Kwc/User/Activate/Form/Success/Component.tpl
Kwc/User/Register/Form/Component.php
Kwf/User/EditRow.php
Kwf/User/Mail/Activation.php
Kwf/User/Model.php

This ways it's possible to allow to continue where the user started.
RedirectUrl forward is implemented like in login-form.
RedirectUrl has to be set in User_EditRow because sendActivationMail is
called in save() function of User_EditRow and not directly in registration
component. It also needs to be an additional parameter for
Kwf_User_Mail_Activation because $row is no User_EditRow and does not have
the redirectUrl field.

Forward redirect parameter from registration-form to activation-form

---

Kwc/Advanced/Youtube/Component.defer.js
Kwc/Advanced/Youtube/Component.php

I created the pull request on behalf of @mike-tuxedo because his github account is currently locked.
The problem is that it doesn't always make sense to continue a paused youtube-video when showing it after it was hidden before. If the video is in a lightbox it may be a favored behaviour when the video is resumed but in our case there is a slider with severals videos in several tabs and the current behaviour causes all stopped videos to play simultanely when reactivating a tab.

Add setting to stop playing the video after it was hide and reshowed

---

composer.json
node_modules_build/kwf-webpack/config/webpack.kwc.config.js

webpack build adds generated promise code in deps and this crashes in ie11

load es6-promise polyfill by default

---

commonjs/frontend-form/form.js

If this.config.hideFormOnSuccess is set to true, this.el will be set to display: none; and therefore it has no topoffset anymore. For example, if the form is in the middle of the page and sending via ajax is complete, it will scroll to the top off the page, because topoffset is 0. But what we realy want is to scroll to the top of the form, to see the successmessage.

Fix for wrong topoffset on success

---

Kwf_js/EyeCandy/Tabs/Tabs.js

When the active tab changes, the content of the tab wish was previous active will be hided. For that content, our standard "hide"-event has to be fired.

Call the hide-event on previous active tab, when active tab changed

---

Kwc/Menu/Abstract/Events.php

Problem was when a menu showed entries from a box beneath the page, when this content changed
the menu cache has to be deleted without a page event being triggered.

Make deleting cache for menu component callable for menu components

---

Kwf/Assets/CommonJs/Provider.php

problem is that third argument of strpos returns pos relative to original haystack
but we only need it from the package name

fixed substr of npm organisation package name

---

Kwf/Util/ModelSync.php

every 100 row delete model row caches because ModelSync caches every row in own array $existingRows

Improved Kwf_Util_ModelSync for big data

---

Kwc/Mail/Abstract/Component.php
Kwc/Mail/Redirect/Component.php
Kwf/Component/Data.php

Mails obviously need to have absolute urls, when preliminaryDomain is set server.domain is usually not yet online.
This changes mails to use preliminaryDomain if one is set.
Caches should be no issue because the link replacement is not cached (as it has to be done for every use) and the img replacement
is also not cached as it is the last step.

Fix Mails when using preliminaryDomain

---

Kwc/Mail/Abstract/Component.php
Kwc/Mail/Redirect/Component.php
Kwf/Component/Data.php

Reverts koala-framework/koala-framework#678
Problem with this PR is that when the web actually goes online and the config setting preliminaryDomain is not removed (which happens to occur) the mails will use the preliminaryDomain in production mode which results in showing an authentication dialog in the client.

Revert "Fix Mails when using preliminaryDomain"

---

Kwc/FulltextSearch/Search/ViewAjax/SearchForm/Component.php

Extend Kwc_Form_NonAjax_Component because FulltextSearch uses removed functions of Kwc_Form_Component

NonAjax Form instead of Form

---

Kwc/User/Login/Component.twig

This field should be renamed to formOptionsHtml, but this would be
an incompatible change and shouldn't be done in a stable branch.

Login formOptions are html and need to be raw in twig to work.

---

Kwf/Controller/Action/Auto/Grid.php

Sometimes the url is not set and causes an exception, which breaks the export.

Require url to render clickable link in AutoGrid excel export

---

Kwc/Shop/Cart/Checkout/Form/Component.css

Defaultsryling makes no sense for a shop that is used in different webs and it's annoying to override it every time.

Remove default styling

---

Kwc/Shop/Cart/Checkout/Form/Component.php
Kwc/Shop/Cart/Checkout/Form/Success/Component.php

Send form per ajax is needed to place the errormessages under the respective input field.

Use ajax to submit checkoutform

---

Kwc/Directories/Item/Directory/Cc/Events.php
Kwc/Directories/Item/Directory/Trl/Events.php
Kwc/Directories/List/EventAbstract.php
Kwc/Directories/List/EventDirectoryChanged.php
Kwc/Directories/List/EventItemAbstract.php
Kwc/Directories/List/EventItemsUpdated.php
Kwc/Directories/List/View/Events.php
Kwc/Directories/TopChoose/Events.php

When source directory is changed in TopChoose the cache for the directory view has to be deleted
Overwriting the view for TopChoose should be avoided so we had to add a generic event to the
directory view which listens for the directory-class and not for the item-directory-class.

Add events for directory view when source directory changes

---

Kwc/Basic/Space/Component.css
Kwc/Basic/Space/Component.tpl
Kwc/Basic/Space/Component.twig
Kwc/Basic/Space/Mail.html.tpl
Kwc/Basic/Space/Mail.html.twig
Kwc/Basic/Space/Mail.txt.tpl
Kwc/Basic/Space/Mail.txt.twig

Some versions of Outlook do not recognize the height attribute,
so the font-size and line-height styles were added.
See: [https://www.campaignmonitor.com/blog/email-marketing/2012/08/outlook-2013-says-no-to-empty-table-cells/](https://www.campaignmonitor.com/blog/email-marketing/2012/08/outlook-2013-says-no-to-empty-table-cells/)
Also remove the unnecessary css file.

Convert tpl to twig for Kwc_Basic_Space_Component

---

Kwc/Newsletter/Detail/Mail/Paragraphs/LinkTag/Abstract/Mail.html.twig

Previously the componentLink would render a link that would use
the componentName of the target as the link text.

Render a link-tag instead of a componentLink

---

Kwc/Basic/Text/StylesModel.php
Kwf/Assets/WebpackConfig.php
Kwf/Controller/Action/Cli/Web/ClearCacheWatcherController.php
Kwf/Util/Build/Types/Assets.php
Kwf/View/Helper/Assets.php

as this is needed to test several integrations of kwf-webs in
external systems.

Enable webpack build to support local https (without certificate)

---

Kwc/Directories/List/Trl/Component.php

Somehow this function is called (after kwf 3.7)but wasn't existing

Fix missing function in directory_list_trl component

---

Kwf/Controller/Action/User/BackendActivateController.php

redirect missed parameters like authMethod and code. As this is
also a security problem this feature is removed.

Fix backend activation with single redirect-auth method

---

Kwc/Tags/Component.php
Kwc/Tags/ComponentToTag.php
Kwc/Tags/Events.php
Kwc/Tags/Suggestions/Controller.php
Kwc/Tags/Suggestions/Model.php

Has originally been fixed in 3.7 (ba72df8f62d8a4aaba2da080afb7b63f5cca6f2b) but is also needed in older webs so I cherry-picked the commit.

when tag is suggested, show this only when it is accepted

---

Kwc/Basic/LinkTag/Intern/Events.php

100 is too little for bigger webs (which then run into a timeout when deleting everything)

Increase limit for linked target count in link intern events

---

Kwc/Basic/Text/Component.php
Kwc/Basic/Text/Mail.html.tpl

This was a legacy feature that was replaced by a better solution a long time ago.
Use the 'getHtmlStyles()' feature of Kwc_Mail_Component instead.

Remove emailStyles from Kwc_Basic_Text_Component

---

Kwc/Root/Abstract.php
Kwf/Component/Data/Root.php

Can be used for javascript applications that use their own routing.
Only possible for static pages directly under root

Add matchChildUrls generator flag that allows a component to 'eat' alll child urls

---

Kwf/Util/Setup.php

Prevents redirect chains (e.g. http://xyz.com => http://www.xyz.com => https://www.xyz.com)

Redirect directly to https if supported

---

Kwf/Component/Abstract/ContentSender/Default.php
Kwf/Component/Plugin/Interface/Redirect.php
Kwf/Component/Plugin/LoginRedirect/Component.php

Using ViewReplace plugin for a redirect (using header('Location... and exit) never has been a good idea.
It is a practical problem now with ContentApi where we get the redirect for the api request.
This change adds a new Redirect Plugin Interface that allows a plugin returning a redirect url. This is done before
rendering and processInput (which will solve a few problems we had there with unauthenticated users)
Downside of this change: it only works when the plugin is at page level

Implement LoginRedirect not in View Plugin

---

node_modules_build/kwf-webpack/config/webpack.kwf.config.js

This adds version-parameter to defer.js file, other files are not
effected. Therefore we still need hash: true in webpack.kwc.config.js
Adding [chunkhash] as parameter to filename param (currently [name].js)
would work for Frontend.js but does not consider changes in de.Frontend.js
requiring some more changes (e.g. improvement of parameter added
in trl-html-webpack-plugin.js) in kwf build code.

Add chunkhash parameter to chunkFilename for cache-busting

---

Kwc/Statistics/Analytics/Component.tpl

Prior to 3.4 anonymizeIp was set, the imprint text still says that it is set and management says that it should be set without the possibility to change the behaviour.
This is to be merged up to 5.1

Anonymize IP for Google Analytics

---

commonjs/cookie-opt/adapter.js

Previously the old value would be returned after setting the new value.

Return the correct cookie-opt value

---

Kwf/Util/Build/Types/Assets.php

This is only required for dev-builds.

Remove the https parameter from the build command

---

Kwc/Root/Abstract.php
Kwc/Root/MaintenanceJobs/DeleteOldEnquiries.php
config.ini

By default all enquiries older than one year will be deleted.
If the enquiries should never be deleted, set the config setting
"enquiries.deleteAfterDays" to false.

Add daily maintenance-job to delete old enquiries

---

KwfBundle/HttpFoundation/Session/KwfSessionStorage.php

errors since 2.8.41 when logged in

symfony session save handler must be wrapped in SessionHandlerProxy

---

Kwc/Box/MetaTagsContent/OpenGraphImage/Component.php
Kwc/Box/MetaTagsContent/OpenGraphImage/Component.tpl

To let facebook catch an previewimage from an https websitelink, the metatag og:image:secure_url has to be set.

Use https-url for image if available

---

Kwc/List/Gallery/Component.scss

so images don't disapear under 600px (mobile)

gallery-component: add 'width: 100%' to col1

---

KwfBundle/HttpFoundation/Session/KwfSessionStorage.php

Reverts koala-framework/koala-framework#834
This didn't actually fix the problem we had since symfony 2.8.41 instead caused issues with php 5.3 (where \SessionHandlerInterface is not defined)

Revert "symfony session save handler must be wrapped in SessionHandlerProxy"

---

Kwc/Directories/List/Trl/Component.php

Can it be that we've never had a trl-directory with partial-id?
I can't really imagine that we didn't have this issue before.

Add getItemIds for Trl-Directory

---

Kwf_js/Auto/GridPanel.js

BaseParams should not be changed if reference is used as this persists
changes to this.baseParams. In our case onDelete added id-param to baseParams
resulting in attempt to load non-existing row in onAdd action.

Fix problems with baseParams

---

Kwf/Dao.php
Kwf/Test.php

as this needed to support saving and loading emojis from database.
It's still required to change database column type to unicode_utf8mb4

Change db-connection configuration to support utf8mb4

---

Kwf/Assets/Dispatcher.php
Kwf/Media/Output.php

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding
"none" isn't a valid value and since a while facebook won't share the image sent with a wrong content-encoding value.

Set encoding to allowed value

---

Kwf/Model/Db.php

This resultet in sql-exception "Unknown column 'xxxx.id' in 'where clause'"
This got lost with phabricator change. Commit-id in phabricator:
6f8f2def6173294dd21f808028f4bc8dab87e434
Author-Date: 15.12.2017 09:11; Branch 3.9.
Previous commit  in phabricator is existent. (827d05f7d2c0996e4aba6dbc9d7155cff5c5a460)

Fix problem with Child_First-Expression and not using tableNameAlias

---

Kwf/Controller/Action/Cli/Web/MaintenanceJobsController.php
config.ini

Currently the maintenance job logs (runs) are kept for 7 days. In some cases a user may want to keep the log files for a longer period.

Define new config-param "maintenanceJobs.timeToKeepPreviousRunsInDays"

---

Kwf/SymfonyKernel.php
config.ini

Before the allowed envs were limited to prod, dev and test. If you need more or different envs you have to overwrite the constructor. With $allowedEnvs you can customize your allowed envs in your Child Kernel without overwriting its parent constructor.

Add protected property $allowedEnvs to Kwf_SymfonyKernel

---

Kwc/Chained/Trl/Component.php

Otherwise every component wich defines anchors has to be translated even though the anchors themselves don't have to be translated.

Add native support for Anchors in Trl-Component

---

Kwc/Basic/DownloadTag/Trl/Events.php

It's only set when it's marked in backend

Access field only when set

---

Kwc/Abstract/Image/DimensionField.php

width can be the value contentWidth when an FullWidthImage is used as
a subcomponent in a custom grid-form because setCreateMissingRow is not
used and so the contentWidth is not set via Kwc_Abstract_Image_ImageFile
(which then replaces the contentWidth value in the js-files).

Check for number value

---

Kwc/Basic/DownloadTag/Trl/Events.php

Own child component has same class so it can happen that in goes into
this codepath

Delete cache only when chained component is changed

---

KwfBundle/EventListener/ExceptionHandler.php
KwfBundle/Resources/config/services.yml
KwfBundle/Validator/ErrorCollectValidator.php
KwfBundle/Validator/ValidationException.php

extended also exceptionHandler to normalize these errors
Usage:
```
$errors = $this->validator->validate($paramFetcher);
if (count($errors) > 0) {
$exception = new ValidationException();
$exception->setErrors($errors);
throw $exception;
}
```
OR
```
$this->validator->validateAndThrow($paramFetcher);
```

added validator for parsing all errors from paramFetcher

---

Kwc/NewsCategory/Model.php

It's already used in Kwc_NewsCategory_Category_Directory_NewsToCategoriesModel
but was not in Kwc_NewsCategory_Model. For this reason it was not possible
to listen to changes (event.php-listener) in Kwc_NewsCategory_Category_Directory_NewsToCategoriesModel.

Fix wrong relation.

---

Kwf/Util/Geocode.php

A new config setting googleServerToServerApiKey is introduced to handle
server to server requests (e.g Google Geocode API or other APIs that don't
support http-referrer restrictions). This key shall not not be exposed to
the client because it might not be restricted. For client-exposed keys the
config setting googleMapsApiKey remains.

Update Kwf_Util_Geocode to use api-key for google-geocode-requests

---

Kwc/Directories/Item/Directory/Trl/FormController.php
Kwc/Form/Dynamic/Trl/Form.php

prevents parent compatibility exceptions

add 'array $info' with default value to 'load'-functions

---

Kwc/TextImage/Component.js

this breaks TextImage with image-dimension = original and order right
or left as width=50% is not applied.
Commit introducing this bug: 8afee1c5ad411e8fe49057cbca26dee4ddc05a17

TextImage: JS code to add gt420 class got accidently removed in 2015

---

Kwc/Form/Dynamic/Component.php

because extconfig contains tabs for paragraphs and form. therefore
no need to add extra button to edit-dropdown

Remove editComponent paragraphs,

---

Kwf/Srpc/Client.php

curl-adapter solves this problem unknown problem for some unknown reason.
Request for rtr check works for argument-length=5683 but fails
for argument-length=5716

Fix randomly defect request,

---

Kwf/Auth/Adapter/PasswordAuth.php
Kwf/Util/BruteForceCheck.php

saves brute-force count in cache with timeout. BruteForceId is
generated from calling location to simplify usage. To connect
different brute-force checks in code define the same BruteForceId.

Implement brute-force util class

---

sass/Kwf/stylesheets/kwf/css3/_border-radius.scss
sass/Kwf/stylesheets/kwf/css3/_box-shadow.scss
sass/Kwf/stylesheets/kwf/css3/_pie.scss

These mixins are either deprecated or do not work.
Because of the autoprefixer added in 4.1 they can be replaced with normal css.

Remove outdated css3 mixins

---

Kwc/Form/NonAjax/Component.defer.js
commonjs/frontend-form/form.js

Kwc-form needs value from submit button to distinguish between different
buttons clicked in form. (e.g. file-upload button and form-submit button)
this information was lost due to submitting via form.submit().
Fixed problem by removing submit-button onclick-listener to
completely remove js code in submit-process.
It was not desired to remove commonjs/FrontendForm/Form.js because
it also handles initialising form-field js functionality.

Fix NonAjaxForm submit

---

Kwf/Model/Abstract.php

This behaviour makes more sense as returning the first row returned
from database. And since $select->whereId(null) throws error it's
also required to make ParentExpression working.

Return null for parent expression if parent_id is null.

---

Kwc/Abstract.php

Der Inhalt von $select['componentClass'] ist (zumindest teilweise) ein string.
Gibt man count() einen string als argument bekommt man ein Warning.
Beispiel:
```
// PHP 7.1
// OK
var_dump(count('some string') == 1); // true     no warning 
// PHP 7.3 
// PHP Warning:  count(): Parameter must be an array or an object that implements Countable
var_dump(count('some string') == 1); // true     but with warning
```

Avoid warning when unsing count() on string in php7.3

---

Kwc/Chained/Cc/Events.php

Kwc_Chained_Abstract_Component::getChainedByMaster doesn't exist

Fix wrong function call in CC-Events

---

Kwf/Component/Data.php

Bei Rotary (wo sonst) gibt es Domains, aber auch Content, der für alle Domains gilt und direkt unter root liegt. Das hat mit der bisherigen Implementierung nicht funktioniert.

Avoid throwing error for component which are not beneath a domain

---

Kwc/Box/MetaTags/Trl/Component.php

It should only be added when needed.
It was removed in the non-trl component in d4b96bc5248ce5c2e91143e398978d66cc6eff59

Remove canonical url from Trl_Component

---

Kwf/Util/RobotsTxt.php

https://search.google.com/test/mobile-friendly says that all requested resources should be
allowed if they are of importance
Applies to mobile menu, ajax-view

Allow /admin/component/edit in robots.txt

---

Kwc/Basic/DownloadTag/Data.php

This behaviour was to prevent opening the download directly in the
current browser window (even though the we tell the browser to
download the file anyway). Nowadays this workaround should not be
necessary anymore.
Current problem is in mobile-apps when the link is clicked in an
in-app-browser because an empty webview is opened.

Remove window.open in download-tag

---

sass/Kwf/stylesheets/kwf/_background-image-dpr2.scss

This prevents inconsistencies bewteen normal and hi-res screens when
the sizes of the image and the container do not match.

Set background-size at normal device-pixel-ratio

---

Kwf/Util/ModelSync.php

Hiermit wird das Löschen von Rows vermieden, um gezielt mehrere Datensätze hinzuzufügen.

Added ignore deleted flag for modelsync

---

Kwf/Controller/Action.php
Kwf/Controller/Action/Auto/Form.php
Kwf/Controller/Action/Auto/Grid.php
Kwf/Controller/Action/Auto/ImageGrid.php
Kwf/Controller/Action/Auto/Synctree.php
Kwf/Controller/Action/User/UsersController.php

Wrong behaviour introduced in https://github.com/koala-framework/koala-framework/pull/881/files
Error occured in XLS-Export when the non absolute url was called in an I-Frame
(XHR-Requests were not affected)

Make sure that controllerUrl is absolute

---

Kwc/Menu/Mobile/Events.php

if a subpage is available, the submenu transition is available, but if you hide all subpages then the transition is still working which is wrong
because of that we have to delete the cache of the parent page too to disable the transition for the submenu

fix mobile menu cache problem

---

Kwf/Model/Db.php

by checking with array_key_exists instead of isset because if type is
not defined in _getTypeFromDbType null is cached.

Improve performance for Db_Row->__get()

---

commonjs/google-map/loader.js

Without the symbol-polyfill, the mapimages-urls are wrong in IE11, because of an undefined value in it. As a result, the images can't be loaded. There is an open issuetracker for this problem https://stackoverflow.com/questions/57623843/googlemaps-sorry-we-have-no-imagery-here-in-internetexplorer-11/58019951#58019951 and https://issuetracker.google.com/issues/139888746

Since Googlemap v3.37 and Koalaframework 5.1, the mapimages couldn't load in IE11.

---

Kwc/Root/Category/Generator.php

Because of page-history it's possible that pageData is returned
even though the parentData is not valid. Without this commit the
"wrong" parentData was set and the exactMatch-value in Kwf_Setup
was not set to false.

Doublecheck parentData and reset if necessary

---

Kwc/Errors/Component.php

This name will be shown in the page title and breadcrumbs instead of the component-key.

Set name for not-found and access-denies pages

---

commonjs/double-tap-to-go.js

remove touchevent test of modernizr because it gets removed in 4.0 modernizr in the future according to the (README.md) but already was removed in 3.8

fix touchevent deprecation of modernizr

---

Kwc/Directories/List/Cc/Component.php
Kwc/Directories/List/Trl/Cc/Component.php
Kwc/Directories/List/Trl/Component.php

Error occured when getSelect was overwritten in master item directory because
it wasn't used in chained components
Also removed failed first fix for this.

Use getSelect from master item directory component

---

Kwf_js/Auto/FormPanel.js

Happens e.g. with Kwc.Basic.ImageParentEditable which normally returns null

Do not encode null value as it results in 'null'

---

composer.json

Modernizr 3.8 deprecates Modernizr.touch and makes build possibly failing
See https://github.com/Modernizr/Modernizr/pull/2472
Removed in Koala 4.5: https://github.com/koala-framework/koala-framework/pull/1016/files

Restrict to compatible modernizr version

---

Kwf/Exception/Abstract.php

Is used in Kwf_Util_Wirecard::processIpn()

Fix wrong interpretation of enable error logging

---

Kwc/Menu/Mobile/Controller.php

Browser can load mobile menu even though e.g. Referer-Header is empty

Deactivate csrf-check for Mobile Menu

---

Kwf/Util/Build/Types/Trl.php

If keys aren't in an ascending order php produces an object instead of an array in json_encode

Fix writing languages.json

---

Kwc/User/Activate/Component.php
Kwc/User/Login/Component.php
Kwf/Controller/Action/User/BackendActivateController.php
Kwf/Controller/Action/User/BackendLoginController.php

Url in html does not need to be url-encoded, so remove this step. $_GET
is always url-decoded so we need to encode it again before adding it to
state parameter.

Fix wrong encoded redirect urls

---

Kwc/User/Login/Plugin.php

as this step is done by the browser on submit or get, resulting in
double urlencoding leading to problems.

Params in html do not need to be urlencoded

---

Kwf/Model/Union.php

Only apply for models with existing dependent-rule. Return null for
others to don't lock them out (if needed it can be done with other
select statements)

Implement union child expression

---

Kwf/Model/Union.php

this way it's possible to make model-specific queries. This does not
work for deeper levels of if-expressions. To implement switch-like
behaviour for a union-model with more than two mixed models use
boolean-expression=true as else statement and define the model-specific
expressions on the same level:
if (model1) ? model1-specific-expression : true;
if (model2) ? model2-specific-expression : true;
if (model3) ? model3-specific-expression : true;
required for pobatis to filter for domain. kwf-users do have only one
domain, pn-users do have multiple domains. There is also a different
database structure required for pn-users (pn-users => functions
(containing domain and company)).

Implement union-model specific if-expression

---

Kwf_js/Auto/FormPanel.js

Reverts koala-framework/koala-framework#1029
This causes null-params to not be sent at all in Ext.Ajax requests, which for example results in select "no selection" not to be sent to json-save.

Revert "Do not encode null value as it results in 'null'"

---

Kwc/Basic/Text/Row.php

since 7.2.0, Usage of parse_str() without a second parameter now emits an E_DEPRECATED notice

Add result param to parse_str in basic text row

---

Kwf_js/Grid/GridView.js

Add padding to headerIcon column to avoid text overlapping the icon

---

Kwc/Shop/Cart/Checkout/Payment/Wirecard/ConfirmLink/Component.php

Wir haben bei Babytuch ein Mail bekommen, dass die Wirecard API mit 22.01.2021 abgedreht und von der Qenta API ersetzt wird. Dabei ist nur die Domain zu tauschen, der Rest der API bleibt gleich.

Change Wirecard to Qenta

---

Kwc/Paging/Abstract/Component.php

ViewCacheSettings of parent can be null.

Prevent error when passing null into array_merge

---

Kwf/Controller/Action/Cli/Web/FulltextController.php

This reverts commit 5584428d3298869615f8b0c0ca3fd0cd353588f3.
Mit der bisherigen Lösung wurden Seiten ohne Content (zB nur mit einem iFrame) aus der kwf_pages_meta Tabelle gelöscht, wodurch sie auch nicht mehr in der Sitemap waren.

Revert "properly delete removed page from Fulltext MetaModel"

---

Kwc/Menu/Mobile/Controller.php

does not correctly detect FirstChildPage and displays link to this kind
of parent-page in navigation next to children.

Fix trl version of mobile-menu

---

Kwf/Controller/Action/User/UsersController.php
Kwf/User/EditModel.php

Since data from the grid-controller is sent to the frontend over an API,
password hashes will be exposed in the browser by adding the password column
to a controller. This poses a security risk and should therefore be avoided.

Avoid usage of password column in grid-controller

---

Kwc/Basic/Text/Component.twig

Problem was that whitespaces were introduced between content parts, sometimes resulting
in visible whitespaces as well.
See https://symfony.com/blog/better-white-space-control-in-twig-templates

Improve whitespace-control in text-component

---

Kwf/Component/Data.php

To get the real url of a page and not the overwritten one from FirstChildPage

Add getOwnUrl, not overwritten by FirstChildPage

---

Kwf/Controller/Action/Component/PreviewController.php

- Validate given url
- Allow only hosts for the current web
The value of the "url"-parameter is used as src in an iframe-tag. Without validation it is possible to format the url like `http://0wn.at:8443/"onload="alert(document.cookie)` which causes to close the src-attribute and creating an onload attribute.

Fix preview XSS

---

Kwf/Acl.php
Kwf/Acl/Component.php

Wie in PEN-Test Besprechung vereinbart, die Einschränkung auf explizite Dateitypen standardmäßig im Koala.
* Dateitypen können in der Acl per _getMediaUploadAllowList() erweitert/entfernt werden.
* Maximale Dateigröße kann in der Acl überschrieben werden.

Add whitelisting for media-uploads

---

Kwf/Util/Fulltext/Backend/Solr.php

try to prevent Log4J CVE-2021-44228

fix: escape query string for solr search

---

Kwf/Controller/Action/Cli/Web/FulltextController.php

because if subroot is not found root is used which results in error

Fulltext-Search find subroot with ignoreVisible

---

Kwc/Basic/DownloadTag/Trl/Component.php

Add functions getFileRow and getFilesize to basic download tag trl component to enable correct use of apiContent

Add functions for apiContent to download tag trl component

---

Kwf/Controller/Action/Cli/Web/ComponentPagesMetaController.php
Kwf/Controller/Action/Cli/Web/FulltextController.php

This caused issues when indexing large amounts of data.
If a memory-limit is really necessary for some reason, this could be done manually in bootstrap.php.

Remove memory-limits from fulltext-rebuild

---

Kwc/TextImage/Mail.html.tpl

image tag can have display:block so wrapping div is required.

Additional styling for text-image center image styling

---

Kwf/Component/Abstract/ContentSender/Lightbox.php
Kwf_js/EyeCandy/Lightbox/Lightbox.js

- when lightbox was opend on reload and then be closed the page title was undefined
- when lightbox was opend on click the page title does not changed to lightbox page title

bugfix lightbox title

---

Kwf/Util/PayPal/Ipn.php

Seit ca. 1 Monat gingen PayPal IPN Requests nicht mehr durch und der Grund war, dass die $_POST Variable auf einmal leer war. Vielleicht hat PayPal was daran geändert, wie sie den Request schicken. Auf jeden Fall funktioniert es so wieder.

Read php input instead of POST because POST is empty

---

Kwc/Basic/Svg/Component.php
Kwc/Basic/Svg/Component.twig

This allows for local development without the need for the production uploads.

Prevent exception when rendering svg that does not exist in uploads

---

Kwc/Basic/LinkTag/Intern/ApiContent.php

E.g. Kwc_Basic_LinkTag_FirstChildPage_Component does not have a 'apiContentType' setting by default.

Prevent exception during api-request when 'apiContentType' is not set

---

Kwf_js/Form/HtmlEditor.js

indenting bullet lists causes invalid ul/li sequence, with this setting the lists get repaired
see: https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@fix_list_elements/

add fix_list_elements to tinymceEditor settings,

---

Kwf/User/MessageRow.php

Summary:
- created a function that get user data of users flagged deleted for the log messages and falls back to a replacement string if the user was actually deleted instead of flagged deleted

Fix for messages with deleted user

---

Kwf/Component/Abstract/ContentSender/Lightbox.php

This allows customizing which page will be rendered behind the lightbox.

Allow overriding 'getParent()' in lightbox content-sender

---

Kwc/TextImage/Form.php

as some languages require more space. now it's the same as the drop-region of image-fileupload

Increase with for options

---

Kwf_js/EyeCandy/Lightbox/Lightbox.js

- when open lightbox the title changes to lightbox title but is undefined when closing lightbox
- 1148 fixed bug when lightbox url is loaded directly and got no title when closing
- now both is supportet

use closeTitle like before fix 1148 when no data-parent-title
