koala-framework/koala-framework

Kwc/Blog/Detail/Component.tpl
Modified template to make it possible to hide the "posted by author" line with css
=> Modified Blog detailview template

trl.xml
=> Fixes and updates to trl.xml 

Kwc/Basic/BackgroundWindowWidth/Component.defer.js, Kwc/Basic/BackgroundWindowWidth/Component.php, Kwc/Basic/BackgroundWindowWidth/Component.scss, Kwc/Basic/BackgroundWindowWidth/Component.twig, Kwc/Basic/BackgroundWindowWidth/ExtConfig.php, Kwc/Basic/BackgroundWindowWidth/Form.php, Kwc/Basic/BackgroundWindowWidth/Image/Component.php, Kwc/Basic/BackgroundWindowWidth/Image/Component.twig, Kwc/Basic/BackgroundWindowWidth/Model.php, trl.xml
Add Basic_BodyWidhtBackground Component
- Choose a background color (default: white / grey / black)
- Upload a background image
- Add margin to bottom
- extandable with Kwc_Parallax
=> Add background settings for paragraphs group component

Kwc/Statistics/Analytics/Component.php, Kwc/Statistics/Analytics/Component.tpl, Kwc/Statistics/Piwik/Component.php, Kwc/Statistics/Piwik/Component.tpl
this is better for debugging purpose
=> Comment out the analytics code instead of not showing it at all

Kwf/Assets/Dependency/File.php, Kwf/Assets/Dependency/File/Scss.php, Kwf/Component/Renderer/Twig/TemplateLocator.php, Kwf/Util/Aws/AutoScaling.php, Kwf/Util/Aws/CloudWatch.php, Kwf/Util/Aws/Ec2.php, Kwf/Util/Aws/ElastiCache.php, Kwf/Util/Aws/S3.php, Kwf/Util/Aws/Sns.php, Kwf/Util/Aws/Sqs.php, Kwf/Util/Setup.php
I'm not sure if it's a good idea for 3.8...
=> Improve AWS Elastic Beanstalk Compatibility

Kwc/Menu/Mobile/Component.defer.js
re-add menuToggle event to animate custom elements in vertical menu during menuanimation
=> re-add menuToggle event

Kwf/Media/Output.php
Some bots dont send a user-agent resulting in an exception
=> Check if user-agent is set

trl.xml
=> new strings RU translation

Kwf/Loader.php
Adding psr4 to namespaces array. But replacing namespace with path
instead of attaching like with namespaces.
=> Add loader-support for psr4 classes

Kwc/Form/Dynamic/Form/Component.php
Default is still noreply@host
Bugfix: Add check if recipient_cc is set, throws an error on send over stmp
=> Add setting fromMailAdress for Dynamic Form

Kwc/Menu/Component.twig
Add the possibility to add custom content after the last listitem of the menu.
=> Add block in menu

Kwf/Loader.php, tests/Kwf/Loader/Test.php
Currently Kwf_Loader isn't covered by unit tests at all which makes it a pain to fix bugs for it.
This PR tries to refactor it so it can be easily unit tested.
=> Refactor Kwf_Loader to be testable

Kwc/Abstract.php, Kwc/Abstract/Image/Component.css, Kwc/Abstract/Image/Component.js, Kwc/Abstract/Image/Component.php, Kwc/Abstract/Image/Component.twig, Kwf/Assets/Dependency/File/Css.php, Kwf/Assets/Dependency/File/Js.php, Kwf/Assets/Dependency/File/Scss.php, Kwf/Component/Renderer/Abstract.php, Kwf/Component/Renderer/Twig/Environment.php, Kwf/Component/Settings.php, Kwf/Component/View/Helper/BemClass.php, Kwf/Component/View/Helper/ComponentWithMaster.php
- bemClass formatter/helper that outputs class prefixed
- kwcbem__ replacment in css/js
=> Support BEM form component css classes

Kwc/Paragraphs/Component.php, Kwc/Paragraphs/Trl/Component.php, Kwf/Assets/Dependency/File.php, Kwf/Assets/Dependency/File/Css.php, Kwf/Assets/Dependency/File/Js.php, Kwf/Assets/Dependency/File/Scss.php, Kwf/Component/Abstract.php, Kwf/Component/Settings.php, tests/Kwf/Assets/ComponentsOverrideScss/ProviderTestDependencies.ini, tests/Kwf/Assets/ComponentsOverrideScss/Root.php, tests/Kwf/Assets/ComponentsOverrideScss/Test.php, tests/Kwf/Assets/ComponentsOverrideScss/TestComponent1/Component.php, tests/Kwf/Assets/ComponentsOverrideScss/TestComponent1/Component.scss, tests/Kwf/Assets/ComponentsOverrideScss/TestComponent2/Component.override.scss, tests/Kwf/Assets/ComponentsOverrideScss/TestComponent2/Component.php, tests/Kwf/Assets/ComponentsOverrideScss/TestProviderList.php
Activate by creating a Component.override.scss file
=> Implement possibility to not inherit styling from base class

Kwc/Advanced/CommunityVideo/Component.php, Kwc/Advanced/VideoPlayer/Component.php, Kwc/List/Gallery/Component.php
Changed componentCategory of Kwc_Advanced_CommunityVideo, Kwc_Advanced_VideoPlayer and Kwc_List_Gallery components to 'media'
=> Changed componentCategorys

Kwf/Db/Table/Abstract.php
Zend_Db_Statement::_stripQuoted has a few preg_replace that are slow as hell for typical
Zend_Db_Table usage as no prepared statements are used and the whole sql string has to be re-parsed
for every executed statement.
And this also effects Kwf_Model_Db as it's backed by Zend_Db_Table.
Profiling my use case showed >70% wall time for preg_replace caused by _stripQuoted.
Solution is pretty simple: we don't need this Statement shit at all:
we don't use prepared statements when using Kwf_Model_Db
=> Improve Db model performance by avoiding costly regular expressions on sql strings

Kwf/Cache/SimpleStatic.php
Improves performance of cli scripts that can't use apc cache by:
- using filesystem (cache/simple) fallback
- cache in-memory to support best performance for reading the same cache entry multiple times
Improves performance of Maintenance scripts like component-pages-meta
=> Add an extra in-memory cache to Cache_SimpleStatic when apc is not used

Kwf/Db/Table/Abstract.php, Kwf/Db/Table/Row/Abstract.php, Kwf/Filter/Row/FilenameParents.php, Kwf/Filter/Row/Numberize.php, Kwf/Filter/Row/UniqueAscii.php
Db_Table is not used anymore, everything has been converted to Model_Db
=> Remove Db_Table filter support

Kwc/Directories/List/ViewAjax/Component.defer.js
Needed for web to update totalResults for search-params
=> Add js-event for ajax-view loaded

Kwc/Mail/Trl/Component.php, Kwc/Mail/Trl/Mail/Component.php, Kwc/Mail/Trl/Mail/Component.twig, Kwc/Mail/Trl/Mail/Mail.html.tpl, Kwc/Mail/Trl/Mail/Mail.txt.tpl
mail sending will be called from child mail abstract which is a mail,
that get its content from parent
=> mail trl component supports now mail sending ;)

Kwf/Assets/Components/Provider.php, Kwf/Assets/Dependency/File/Scss.php, Kwf/Component/Abstract/Admin.php
load the $config using @import "config";
=> Add possibility to add dynamic config to Component.scss files

Kwc/Directories/List/ViewAjax/Component.defer.js, Kwc/Directories/List/ViewAjax/Component.php
added some new features for the ajax view
=> 3.10 ajax view features

sass/Kwf/stylesheets/kwf/_z-index.scss
Add a z-index mixin to avoid collision with the used z-indices in koala-frontend
=> add sass mixin for better z-index handling

Kwc/Mail/Component.php, Kwc/Mail/Form.php
There are already settings in Mail_Abstract which should be used.
=> Remove default-Settings from Mail_Component

Kwc/User/ChangePassword/Form/FrontendForm.php
Remove double new password input fields of change password component
=> Change password double input

Kwf/Model/Abstract.php
it did not return proxied model or models connected through unionModel
=> Fix bug with Kwf_Model_Abstract::findAllInstances()

Kwc/Abstract/Image/Form.php, Kwc/Abstract/Image/ImageUploadField.js, Kwc/Abstract/Image/ImageUploadField.php, Kwc/Basic/ImageParentEditable/Component.php, Kwc/Basic/ImageParentEditable/Form.php, Kwc/Basic/ImageParentEditable/ImageFile.js, Kwc/Basic/ImageParentEditable/ImageFile.php, Kwc/Basic/ImageParentEditable/ImageUploadField.js, Kwc/Basic/ImageParentEditable/ImageUploadField.php
shows default image from parent but allows a custom crop area or a custom image
=> Implement ImageParentEditable

Kwc/Basic/ImageEnlarge/Component.scss, Kwf/Assets/Dispatcher.php, Kwf/Assets/Filter/Abstract.php, Kwf/Assets/Filter/Css/AbstractPostCss.php, Kwf/Assets/Filter/Css/Ie8Only.js, Kwf/Assets/Filter/Css/Ie8Only.php, Kwf/Assets/Filter/Css/Ie8Remove.js, Kwf/Assets/Filter/Css/Ie8Remove.php, Kwf/Assets/Filter/Css/PostCssRunner.php, Kwf/Assets/Package.php, Kwf/Controller/Action/Cli/BuildController.php, Kwf/Util/Build/Types/Assets.php, Kwf/Util/ClearCache/Watcher.php, Kwf/View/Helper/Assets.php, composer.json, composer.lock, tests/Kwf/Assets/Filter/Ie8/Test.php, tests/Kwf/Assets/Filter/Ie8/test1.scss
- better performance for 'real' browsers
- avoids too many selectors problems
=> Implement own css file for ie8

Kwc/Abstract/Image/DimensionField.js, Kwc/Abstract/Image/DimensionField.php, Kwc/Abstract/Image/DimensionWindow.js, Kwc/Abstract/Image/ImageUploadField.js, Kwc/Abstract/Image/PreviewController.php, Kwc/Basic/ImageEnlarge/ImageUploadField.js, Kwf/Controller/Action/Media/UploadController.php
Not relative to handyImageSize.
=> Return correct crop sizes

Kwc/User/Login/Component.twig
This block doesn't make sense above everything else.
=> Move lostpassword block into form block

Kwf_js/EyeCandy/Lightbox/Lightbox.js
Fixes issue with Android 4.1 and Escape-Button
=> Fix lightbox bugs

commonjs/frontend-form/field/file.js, commonjs/frontend-form/field/multi-checkbox.js
Change multi-checkbox.js to jquery and fix missing jquery depency in file.js
=> Add jquery and change code accordingly to jquery

Kwf/Model/Abstract.php, Kwf/Model/Db.php, Kwf/Model/Select/Expr/Child/GroupConcat.php, Kwf/Model/Select/Expr/GroupConcat.php, tests/Kwf/Model/DbWithConnection/ExprGroupConcat/ChildModel.php, tests/Kwf/Model/DbWithConnection/ExprGroupConcat/Model.php, tests/Kwf/Model/DbWithConnection/ExprGroupConcat/Test.php, tests/Kwf/Model/FnF/ExprGroupConcat/ChildModel.php, tests/Kwf/Model/FnF/ExprGroupConcat/Model.php, tests/Kwf/Model/FnF/ExprGroupConcat/Test.php
Now it is possible to order the group concat output by a given field.
=> Add order field param to Kwf_Model_Select_Expr_GroupConcat Expression

Kwf/Model/Abstract.php, Kwf/Model/Db.php, tests/Kwf/Model/DbWithConnection/ParentExprDeletedFlag/ChildModel.php, tests/Kwf/Model/DbWithConnection/ParentExprDeletedFlag/ParentModel.php, tests/Kwf/Model/DbWithConnection/ParentExprDeletedFlag/Test.php, tests/Kwf/Model/FnF/ParentExprDeletedFlag/ChildModel.php, tests/Kwf/Model/FnF/ParentExprDeletedFlag/ParentModel.php, tests/Kwf/Model/FnF/ParentExprDeletedFlag/Test.php
it only shows value, getParentRow is not supported for deleted rows
=> Kwf_Model_Select_Expr_Parent ignores deleted flag now

Kwf/Component/Abstract/ContentSender/Default.php, Kwf/Util/Component.php
re-use Kwf_Media_Output as that supports gzipping if the browser supports it. Unfortunately we have content vs. contents
=> Output frontend html gzipped when possible

Kwc/Paragraphs/AddParagraphButton.js, Kwc/Paragraphs/Controller.php, Kwc/Paragraphs/DataView.js, Kwc/Paragraphs/Panel.js, Kwc/Root/Category/Generator.php, Kwf/Component/Generator/Table.php, Kwf/Component/PluginRoot/Interface/DenyAddComponentClass.php, Kwf/Controller/Action/Component/PageController.php
This allows dynamically denying adding of component classes
=> Add DenyAddComponentClass Plugin

commonjs/google-map/loader.js
Now libraries (e.g geometry library) could be required from the google maps api
=> Add libraries parameter to google maps loader

Kwf/Assets/Components/Provider.php, Kwf/Component/Renderer/Twig/Helper.php, Kwf/Component/Renderer/Twig/TemplateLocator.php
- add renderer.getComponentMasterTemplate for inheriting in twig
- add masterExtends setting for inheriting css
=> Add possibility to inehrit master template including styles

Kwf/Assets/Components/Provider.php, Kwf/Component/Renderer/Twig/Helper.php, Kwf/Component/Renderer/Twig/TemplateLocator.php
Reverts koala-framework/koala-framework#543
=> Revert "Add possibility to inehrit master template including styles"

Kwc/FulltextSearch/Search/Directory/Model.php
this can be found in https://wiki.apache.org/solr/CommonQueryParameters#line-60
=> fq query params should start with + and separated with space

Kwf/Trl.php, Kwf/Util/Build/Types/Trl.php
There was to much nonsense output from trl-generation. Now it's only half and more descriptive.
=> Fix trl duplicate flood in build

Kwf/Cache/Backend/Apc.php, Kwf/Util/ClearCache.php, Kwf/Util/ClearCache/Types/ApcOptcode.php, Kwf/Util/ClearCache/Types/ApcUser.php, Kwf/Util/ClearCache/Types/Setup.php, Kwf/Util/Maintenance.php, config.ini
This feature is needed if a website has to scale across different
servers. So that "cc" on one server can clear cache across all of them.
=> Add config settings to define external clear-cache script.

Kwf/Events/Dispatcher.php
This is handy for insert/update/delete events on the same model
=> Add possibility to define callback for multiple event-classes

Kwc/Form/Field/Abstract/Component.php, Kwc/Form/Field/Abstract/UseViewCachePlugin.php, Kwf/Component/Data.php, Kwf/Component/Plugin/Interface/UseViewCache.php, Kwf/Component/Renderer.php, Kwf/Component/Renderer/Abstract.php
try to output cacheable as often as possible
for better reverse proxy (varnish) integration
=> Improve ContentSender public cache

Kwc/Advanced/IntegratorTemplate/Embed/Component.js, Kwc/Advanced/IntegratorTemplate/Embed/ContentSender.php, Kwc/Menu/Mobile/Component.defer.js, commonjs/base-url.js
required for IntegratorTemplate to work correctly with Menu_Mobile
Other alternatives:
* add a parameter in ajaxPrefilter to all ajax requests `absoluteUrls` and handle this on server side
* always use absolute urls
We also have to consider other situations where urls are generated in JS only (porschebankkundenportal)
=> Implement kwf/base-url and use it in Menu_Mobile

Kwf/Component/Cache/Mysql.php, Kwf/Component/Cache/Redis.php, Kwf/Component/Event/ViewCache/ClearFullPage.php, Kwf/Update/20160907CacheComponentUrl.sql
can be used for purging a reverse proxy (varnish) cache
=> Add Event when FullPage view cache is cleared

Kwc/Box/MetaTagsContent/OpenGraphImage/Component.php, Kwf/Util/Fulltext/Backend/Abstract.php
Some optimizations and bugfixes for fulltext-search
=> 4.2 fulltext optimization

Kwf/Component/Abstract/ContentSender/Default.php, Kwf/Exception/Abstract.php, Kwf/Exception/AccessDenied.php, Kwf/Exception/Conflict.php, Kwf/Exception/Logger/LogFiles.php, Kwf/Exception/Unauthorized.php, Kwf/Setup.php, Kwf/Util/Setup.php, views/error-client.tpl, views/error.tpl, views/error403.tpl
Throw correct exception with additional message in setup.php
=> Change AccessDenied to 403, add 401 Unauthorized Exception

Kwc/Newsletter/Detail/Mail/Component.php, Kwf/Controller/Action/Cli/Web/NewsletterController.php
This ways it's easier to change behaviour.
=> Move code from newsletterController into Detail-Mail component

Kwc/Errors/Abstract/Component.php, Kwc/Errors/AccessDenied/Component.php, Kwc/Errors/NotFound/Component.php, Kwf/Exception/Abstract.php
This enables possibility to render exception message.
=> Call setException for ExceptionComponent

Kwf/Assets/CommonJs/Underscore/TemplateDependency.php, Kwf/Assets/Dependency/File/Js.php, Kwf/Assets/Filter/Abstract.php, Kwf/Assets/Filter/Css/AbstractPostCss.php, Kwf/Assets/Filter/Css/Autoprefixer.php, Kwf/Assets/Filter/Css/Ie8Only.php, Kwf/Assets/Filter/Css/Ie8Remove.php, Kwf/Assets/Filter/Css/KwfLocal.php, Kwf/Assets/Filter/Css/MultiplePostCss.php, Kwf/Assets/Filter/Css/PrefixerFontface.php, Kwf/Assets/Filter/Css/PrefixerKeyframes.php, Kwf/Assets/Filter/Css/SelectorReplace.php, Kwf/Assets/Package.php, Kwf/Assets/ProviderList/Default.php
Similar to kwcBem/kwcClass but also works for non-component files
=> Assets replace kwfLocal in any css/js file with class name relative to current file

Kwc/Mail/Abstract/Component.php, Kwc/Mail/Component.php, Kwc/Mail/Form.php, Kwc/Newsletter/Detail/Controller.php, Kwf/Mail.php
- Make use of default email.from.address config setting
- Add possibility to use baseParams for these settings
- Cleaner API
- Get rid of ->clearFrom() when changing address
=> Make mail adresses easer customizable

Kwc/Newsletter/Detail/StatisticsController.php, Kwc/Newsletter/PluginInterface.php
now the plugin has the newsletterRow data for statistics
=> changed getNewsletterStatisticRows param to $newsletterRow

Kwf/User/Model.php
php sessionId was changed but getStorage()->write didn't write because
content was same as before. So php session was still emtpy.
=> Fix loginUserRow(...) for currently loggedin user did logout.

Kwc/User/Edit/Form/FrontendForm.php, Kwc/User/Register/Form/Component.php, Kwf/User/EditModel.php, Kwf/User/Form.php
Complex work arounds with createUserRow are obsolete because global user service was already removed
=> Reactivate createRow function in Kwf_User_Model

Kwf/SymfonyKernel.php
this allows us using symfony services everywhere.
=> Add getInstance method for symfony kernel

Kwf/Acl/Component.php
Deny welcome contro**lel**r to normal users per default
=> deny access to welcome controller to normal users by default

Kwf/Acl/Component.php
Reverts koala-framework/koala-framework#638
=> Revert "deny access to welcome controller to normal users by default"

Kwf/Controller/Action/Cli/Web/MaintenanceJobsController.php, Kwf/Util/Maintenance/Job/Abstract.php
it's possible now to start a maintenance job every time you want
you only have to override getNextRuntime and return new timestamp when job has to start
=> added new maintenance job frequency called CUSTOM

Kwc/Basic/LinkTag/BlogPost/DirectoriesController.php, Kwc/Basic/LinkTag/News/DirectoriesController.php
for example when news content links to other news content
=> fixed error when linking to a page with dbIdShortcut

Kwf/Util/Maintenance/Dispatcher.php
this is more helpfull than exitCode
=> Add errorOutput to log-information

Kwc/Newsletter/Subscribe/Update/20170819SubscriberLogState.php
Current solution was slow and caused a memory limit error above 100k subscribers
=> Accelerate logs update for newsletter subscribers

node_modules_build/kwf-webpack/loader-kwc/component-file-loader.js
=> don't replace kwcBem, only replace kwcBem__ and kwcBem--

Kwc/Newsletter/Unsubscribe/Form/Component.php
processInput is not supported anymore in Kwc_Form_Component
=> fixed unsubscribe component by activating processInput flag

Kwf/Util/ModelSync.php
Cherry Pick from 4.2
needed because the new model sync exceeds memory limit on audi
=> Improved Kwf_Util_ModelSync for big data

Kwf/Component/Abstract/ContentSender/Default.php
Problem was that when set to DENY the preview doesn't work
=> Allow embedding in Frames from same origin

Kwf/Assets/Webpack/Chunk.php
=> added helper class to get contents of builded webpack chunk

Kwc/Shop/Products/View/Component.php
Since AddToCart-Components are AjaxForms this is not necessary anymore
=> Remove forwarding processInput to AddToCart-Component

Kwf/Controller/Front.php
not possible using Cli Controllers because we this would dispatch into action methods for sub commands
=> Add vps symfony command that starts a child process with symfony console

Kwc/Shop/Box/Cart/Component.defer.js, Kwc/Shop/Box/Cart/Component.tpl, Kwc/Shop/Products/Directory/AddToCart/Component.php
Converted the javascript from Kwc_Shop_Box_Cart_Component from extjs to jquery
=> Remove extjs from Cartbox

Kwc/Newsletter/Subscribe/MailEditable/Mail.html.twig
This is so we can add the header and footer blocks as table-rows.
=> Restructure mail template

Kwc/Newsletter/EditSubscriber/Component.php
=> Do not call the parent function

Kwc/Newsletter/Subscribe/MailEditable/Mail.html.twig
This is useful, for example if you want to add a style-tag to the head of the document.
=> Add html tags around mail

Kwf/Media/Output/Component.php
Problem is that Zend_Http_Client_Adapter_Proxy might cause problems with certificates
=> Use curl-adapter if available for getting media source

Kwf/Controller/Action/User/LoginController.php
Target is same as after login as this should redirect to correct
login page (eg front or backend)
=> Redirect after activation without state in session

Kwf/Util/Build.php
With this change packages can define a build step in composer.json that will
be added as step in koala build
=> Add possibility for packages to integrate into kwf build

Kwf/Component/Data/Root.php
Unused feature for years, makes you no-so-happy when you name your project 'dev'
=> Remove magic dev. subdomain handling

Kwf/Util/Build.php
This mistake happened during changing the base branch, sorry
=> Don't build RteStyles twice

Kwf/User/Row.php
added the getAdditionalRolesFunction to the User Row Controller for the User ProxyModel
=> added getAdditionalRolesFunction to User Row Controller for User ProxyModel

Kwc/Basic/Text/Component.tpl, Kwc/Basic/Text/Component.twig, Kwc/Basic/Text/Mail.html.tpl, Kwc/Basic/Text/Mail.html.twig
And add table with rootElementClass for mail template.
=> Convert Kwc_Basic_Text_Component to twig

Kwf/Component/Generator/Abstract.php
Can be used for easier setting eg. showInPageTreeAdmin without having to create a custom generator class
=> Allow setting generator flags thru generator settings

Kwc/Abstract.php, Kwc/Root/Abstract.php, Kwf/Component/Data.php
This was initially created for prosalzburg but has not been used anywhere afaik
=> Remove shortcutUrl feature

commonjs/on-ready.js
Allows usage of callOnContentReady in eg. decoupled child projects
=> Leak callOnContentReady into window.prefix.Kwf

Kwf/Component/Abstract/ContentSender/Default.php
Got broken by https://github.com/koala-framework/koala-framework/pull/778 and was reported in chrome console as error
=> Fix X-XSS-Protection syntax error

Kwc/Directories/Category/ShowCategories/DirectoriesController.php, Kwc/Directories/Category/ShowCategories/Form.php
=> Use remote select for ShowCategories

Kwc/Menu/DropdownMask/Component.php, Kwc/Menu/ScrollButtons/Component.js
- add missing for ScrollButtons js
- DropdownMask deps in component not needed
=> fix jquery deps

Kwc/User/Login/Component.twig
Variable should be renamed, but would be an incompatible change.
=> formOptions are html and should be output as raw

node_modules_build/kwf-webpack/loader-kwc/component-assets-loader.js
only these two needs replacement for kwcBem/kwcClass all others can be required normally
=> use component-file-loader only for Master.* and Component.* files

Kwc/Abstract/Image/Component.php, Kwf/Media/Image.php, config.ini
https://app-eu.wrike.com/workspace.htm?acc=1410363#path=folder&id=-1&c=list&t=242252239&so=14&bso=10&sd=1&f=text%3Dpage-&sq=page-
=> Allow setting a global imageCompressionQuality

Kwf/Util/Setup.php
Prevents redirect chains and in certain cases endless redirects.
=> Redirect directly to https if supported

Kwc/Shop/Cart/Checkout/Payment/Wirecard/ConfirmLink/Component.php
=> Make Wirecard params extensible

Kwf/Media/Output.php
Event though it's not used actively
=> Set encoding to allowed value

Kwf/Model/Db/Row.php
Fixes Bug introduced with 59a49cbd7e5b940e087556503ef1a7b416a5ad3c
=> Execute afterInsert only when inserting

Kwc/Abstract/List/Trl/Generator.php, Kwc/Paragraphs/Trl/Generator.php
Now behaves same as paragraphs
Also use same implementation for paragraphs
=> Use only the trl-visible status for list entries

Kwc/Abstract/Image/Trl/Component.php
Copy code from non-trl version.
=> Fix getImageUrl in Trl

Kwc/Basic/LinkTag/News/Component.php, Kwc/Basic/LinkTag/News/DirectoriesController.php
Introduced by structural changes in https://github.com/koala-framework/koala-framework/pull/641
=> Fix LinktTag_News issues

Kwc/Statistics/OptBox/Component.php, Kwc/Statistics/OptBox/Component.twig
For easier removing in integrator template
=> Mask opt box

Kwc/Shop/Box/CartLink/Component.php
pulls in a lot of Ext2 although the code is already ported to jQuery
=> Remove ExtConnection from frontend dependency

Kwf/Media/Image.php, Kwf/Media/Scaler/Abstract.php, Kwf/Media/Scaler/Gd.php, Kwf/Media/Scaler/Imagick.php, Kwf/Media/Scaler/RemoteService.php
The remote service backend can be useful to run scaling images in an external microservice
=> Refactor image scaling into Scaler backends and introduce a RemoteService backend

Kwf/Util/Build/Types/Trl.php
- separates trl and trlKwf calls if webCodeLanguage=en
- use more distinctive naming for private functions
- fixes issue with webCodeLanguage=en where translations are always read from the kwf-file and where impossible to be overwritten for web
=> split loadTrlArray() into loadWebTrlArry() and loadKwfTrlArray(),

Kwf/Media.php
its possible now to activate lifetime for Cache-Control Headers but not cache file in cache/media
=> New setting disableMediaCache for Kwf_Media_Output

Kwc/Abstract/Cards/Trl/Component.php, Kwc/Basic/LinkTag/Extern/Trl/Component.php, Kwc/Basic/LinkTag/Intern/Trl/Component.php
changing master link-target did not clear cache of trl component
=> Fix LinkTag_Intern_Trl cache bug.

Kwc/Mail/HtmlParser.php, Kwf/Component/View/Renderer.php
replace kwfUp with the unique prefix also in the font-family attribute in the html-style to use the prefixed font package
=> replace kwfUp in the style attributes html-style

Kwf/Mail.php
Remove true from if statement as it always validates to true
=> Fix adding cc to mail

Kwf/Model/Mail/Row.php
We need the possibility to set this header in a contact form for the receiving ticketing system.
=> Support reply-to in Kwf_Mail

Kwc/Shop/AddToCart/Component.defer.js, Kwc/Shop/Box/Cart/Component.defer.js, Kwc/Shop/Products/Directory/AddToCart/Component.defer.js, Kwc/Shop/Products/Directory/AddToCart/Component.php
see https://github.com/koala-framework/kwc-shop/pull/10 and https://github.com/koala-framework/kwc-shop/pull/11
=> Fix updating cart box

Kwf/Setup.php, Kwf/User/Model.php, tests/Kwc/Favourites/UserModel.php, tests/Kwc/FavouritesSelenium/UserModel.php, tests/Kwc/User/BoxWithoutLogin/UserModel.php
- also return authedUser if user not in session (for example if logged in via token)
- change overrides in test-children according to changes in parent
=> Add setAuthedUser function to userModel

Kwc/Abstract/List/Component.twig
This makes it easy to add elements before and after the list-items and inside the item.
=> Add twig-blocks for Kwc_Abstract_List_Component

Kwc/Directories/Item/Detail/Cc/Component.php, Kwc/Directories/List/Cc/Component.php
See https://github.com/koala-framework/koala-framework/pull/742
=> Add missing getItems in CC-Component

Kwc/Columns/Abstract/Controller.php, Kwc/Columns/Abstract/SettingsForm.php, Kwf/Component/Generator/Box/StaticSelect/PagePropertiesForm.php, Kwf/Component/Generator/Static.php
These errors occurred when using PHP 7.1.23
=> Fix error "Only variables should be passed by reference"

Kwc/Events/Directory/Controller.php
Visible was moved to first column so the old solution didn't correctly
=> Positionize columns better

composer.json
for https://github.com/koala-framework/file-watcher/pull/3
=> Change file-watcher dependency to ~1.0

Kwf/Component/Abstract/ContentSender/Default.php
Cherry pick from 5.1 because now needed in older web
=> Make default headers easier configurable

Kwc/Basic/Svg/Admin.php, Kwc/Basic/Svg/Component.php, Kwc/Basic/Svg/Component.twig, Kwc/Basic/Svg/Controller.php, Kwc/Basic/Svg/Form.php, Kwc/Basic/Svg/Model.php, Kwc/Basic/Svg/Update/20190621PrepareSvgTable.php, Kwf/Form/Field/File.php
new KwcBasicSvg Component
Simple Svg file-upload with variable output type - source or url
=> Basic svg component

Kwc/Directories/Item/Directory/Controller.php, Kwc/Directories/Item/Directory/ControllerEditButtonData.php
=> Fix missing editcomponent in button data

Kwc/Menu/Mobile/Component.defer.js, Kwc/Menu/Mobile/Component.scss
added a classname to the list items in the mobile menu list + additionally add a --selected classname modifier if it is the current page
=> mobile menu with selected classname on listitem

Kwc/Abstract/Admin.php, Kwc/Abstract/Image/Admin.php, Kwc/Abstract/Image/Trl/Admin.php, Kwc/Basic/Download/Admin.php, Kwc/Basic/Download/Trl/Admin.php, Kwc/Basic/Headline/Admin.php, Kwc/Basic/Headline/Trl/Admin.php, Kwc/Basic/Html/Trl/Admin.php, Kwc/Basic/Link/Admin.php, Kwc/Basic/Link/Trl/Admin.php, Kwc/Basic/Text/Admin.php, Kwc/Basic/Text/Trl/Admin.php, Kwc/Basic/Textfield/Admin.php, Kwc/Box/TitleEditable/Admin.php, Kwc/Chained/Trl/MasterAsChild/Admin.php, Kwc/Root/Category/Trl/Generator.php, Kwc/Root/CategoryGenerator.php, Kwc/Tabs/Admin.php, Kwf/Component/Generator/Abstract.php
We need this for a 3.10 web which "must not" be updated.
Consists of cherry picks from 21fdbc89f1b8b8a3661e3f4d98102b275993870e and 6db5580b079e054061f805893e51bed46ad8eedd and an own commit
=> Content import export

commonjs/google-map/loader.js
Avoids overwriting callbacks when GoogleMapsField is used in admin
=> Make google-map-loader callbacks global

Kwc/Basic/Text/ApiContentHtmlParser.php
Now the text-api-structure is more generic and compatible with content-api.
component-elements are now always returned like content-api would do but
also support linkTag-components with text-api children.
=> ContentApi: text-api: change component element

Kwc/Paragraphs/Panel.js
Occured when deleting two paragraphs, adding one and set the new one to visible
=> Fix error in Paragraphs Panel

Kwc/Tags/Events.php
see 6f509f14cc06d55137aa9ec8ab2c39ca90ddefe7
=> update event classname after rename,

Kwf/Model/Db.php
currently only union-parent fields could be returned. now it's possible
to add select-expressions (for filtering) based on union-source-model
data/relations.
Db
+---------+
Db             Union    +-->+ PnUsers |...
+----------+   +-------+  |   +---------+
| Attempts +-->+ Users +--+     Db
+----------+   +-------+  |   +----------+
+-->+ KwfUsers |...
+----------+
select Attempts where Parent('Users', ...)
TODO: need to test if it also works for union-model-relations
=> Implement parent select-expression with union parent

Kwc/Box/StructuredData/Admin.php, Kwc/Box/StructuredData/Component.php, Kwc/Box/StructuredData/Controller.php, Kwc/Box/StructuredData/Form.php, Kwc/Box/StructuredData/Model.php, Kwc/Box/StructuredData/Update/20200619KwcStructuredData.sql
Textfield to add JSON for structuredData box rendered in head
...SEO...
=> StructuredData box

Kwf_js/Auto/AssignGridPanel.js
it's required to do it in client because assign-grid controller does not
have any relation to data-grid controller and therefore can not share
server-side code.
=> Add assignAll-Button

Kwf/Media/Output.php
this will work for apache and php-fpm
=> fix: return correct 206 http header

Kwf/Update/20201111FixSessionIdLength.sql
=> Add compatibility with longer session ids

Kwc/Advanced/Youtube/Component.defer.js, Kwc/Basic/DownloadTag/Component.defer.js, Kwc/Box/Title/Component.php, Kwc/Statistics/GoogleTagManager/Component.defer.js, Kwc/Statistics/GoogleTagManager/Component.php, Kwc/Statistics/GoogleTagManager/Component.twig, Kwf/Util/Component.php, Kwf_js/EyeCandy/Lightbox/Lightbox.js, Kwf_js/EyeCandy/List/Plugins/ActiveListener/LargeContentAjax.js, commonjs/data-layer.js, commonjs/frontend-form/form.js, commonjs/view-ajax/view.js
=> Data layer

Kwc/Form/Dynamic/Form/Component.php
below directory with dbIdShortcut
=> Fix send_confirm_mail for dynamic-form,

Kwf/Setup.php, Kwf/Util/RobotsTxt.php, config.ini
=> Allow robots.txt to be overwritten

Kwf/Controller/Action/User/BackendLoginController.php, Kwf/Controller/Action/User/BackendLostPasswordController.php, Kwf/Util/BackendLoginRestriction.php
Add Option to Block Admin Login from everywhere, except selected IPs or IP Ranges.
=> Add option to block /admin from external IPs

config.ini
=> update application kwf version in config.ini

KwfBundle/Validator/Constraints/NoTags.php
=> Init message-value only once

Kwc/Menu/Cc/Events.php
changing page-title did not clear cache of cc-menu components
=> Fix cache-issues with menu-cc component

Kwc/Menu/Cc/Events.php, Kwc/Menu/OtherCategory/Cc/Events.php, Kwc/Menu/ParentMenu/Cc/Events.php
Just do the same with Cc like Trl does for every menu component
See https://github.com/koala-framework/koala-framework/pull/1129
=> Fix bugs introduced with 1af75ca18bfc01c2444b05cf4838c1b1ac7372fb

Kwc/Mail/Editable/Trl/PreviewController.php, Kwc/Mail/PlaceholdersPlugin.php, Kwc/Mail/Trl/Component.php, Kwc/Mail/Trl/PreviewController.php, Kwf/Component/Plugin/Placeholders.php
languages can be hidden so ignoreVisible flag is needed
=> fix: mail editable component for trl usage

Kwf/Component/Plugin/AccessByMail/Form/Component.php
processInput was not called anymore because parent did remove the flag
=> Fix access-by-mail component

Kwf/Media/Output.php
as this does not comply etag specification, as it never changes if the
content changes
=> Remove static etag header

Kwf/Media/Image.php, Kwf/Media/Scaler/Abstract.php, Kwf/Media/Scaler/Imagick.php
16 bit Images are 10-times bigger in size.
=> set image channel depth to 8 bit to reduce unwanted 16 bit images and remove duplicate code

Kwf/Controller/Action/Cli/Web/ComponentPagesMetaController.php
otherwise it might happen that the process runs into memory-limit of 128M
=> Create child process earlier

Kwc/Basic/Headline/Component.php
call decode to support manually encoded strings
=> HTML-Encode headline string

Kwf/User/MessageRow.php
Summary:
- add info that the change was made by the system if `ip` contains `cli`
- add a censored version of the ip if it contains an ip that is not `cli`
=> Adjustment for additional info in the log messages

Kwf/Exception/Abstract.php, Kwf/Exception/Unauthorized.php, Kwf/Setup.php
Happened when an error occured while rendering
Prior branches will get a seperate PR
=> Do not leak prelogin-password

Kwf/View/Helper/HighlightTerms.php
this is the branch where the error needs to be fixed for a project.
=> Quote term for regex to highlighting terms

Kwf_js/EyeCandy/Lightbox/Lightbox.js
- add title change on show function
- add data parent title for lighbox div - same as in php variant
- add title change on close function
- including chrome bug where Html-Title is not changed visibly after 2nd time closing but in Html already
=> fix Lightbox title bug

Kwf/Controller/Action/User/LoginController.php
to solve cookie-restriction problem
=> Change last redirect to client-side initiated
